In [3]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
from scipy import stats

In [8]:
df=pd.read_csv("US_Accidents_May19.csv")
df.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201,3,2/8/2016 5:46,2/8/2016 11:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201,2,2/8/2016 6:07,2/8/2016 6:37,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201,2,2/8/2016 6:49,2/8/2016 7:19,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201,3,2/8/2016 7:23,2/8/2016 7:53,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201,2,2/8/2016 7:39,2/8/2016 8:09,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [6]:
m = df['Severity'].mean()
df['Severity'].fillna(m, inplace=True)
m = df['Start_Lat'].mean()
df['Start_Lat'].fillna(m, inplace=True)
m = df['Start_Lng'].mean()
df['Start_Lng'].fillna(m, inplace=True)
m = df['Distance(mi)'].mean()
df['Distance(mi)'].fillna(m, inplace=True)
m = df['Temperature(F)'].mean()
df['Temperature(F)'].fillna(m, inplace=True)
m = df['Wind_Chill(F)'].mean()
df['Wind_Chill(F)'].fillna(m, inplace=True)
m = df['Humidity(%)'].mean()
df['Humidity(%)'].fillna(m, inplace=True)
m = df['Pressure(in)'].mean()
df['Pressure(in)'].fillna(m, inplace=True)
m = df['Visibility(mi)'].mean()
df['Visibility(mi)'].fillna(m, inplace=True)
m = df['Wind_Speed(mph)'].mean()
df['Wind_Speed(mph)'].fillna(m, inplace=True)
m = df['Precipitation(in)'].mean()
df['Precipitation(in)'].fillna(m, inplace=True)

In [7]:
df._get_numeric_data()

,TMC,Severity,Start_Lat,Start_Lng,Distance(mi),Number,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),...,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop
0,201,3,39.865147,-84.058723,0.01,NaN,36.9,33.094733,91.0,29.68,...,False,False,False,False,False,False,False,False,False,False
1,201,2,39.928059,-82.831184,0.01,2584.0,37.9,33.094733,100.0,29.65,...,False,False,False,False,False,False,False,False,False,False
2,201,2,39.063148,-84.032608,0.01,NaN,36.0,33.300000,100.0,29.67,...,False,False,False,False,False,False,False,False,True,False
3,201,3,39.747753,-84.205582,0.01,NaN,35.1,31.000000,96.0,29.64,...,False,False,False,False,False,False,False,False,False,False
4,201,2,39.627781,-84.188354,0.01,NaN,36.0,33.300000,89.0,29.65,...,False,False,False,False,False,False,False,False,True,False
5,201,3,40.100590,-82.925194,0.01,NaN,37.9,35.500000,97.0,29.63,...,False,False,False,False,False,False,False,False,False,False
6,201,2,39.758274,-84.230507,0.00,376.0,34.0,31.000000,100.0,29.66,...,False,False,False,False,False,False,False,False,False,False
7,201,3,39.770382,-84.194901,0.01,NaN,34.0,31.000000,100.0,29.66,...,False,False,False,False,False,False,False,False,False,False
8,201,2,39.778061,-84.172005,0.00,99.0,33.3,33.094733,99.0,29.67,...,False,False,False,False,False,False,False,False,False,False
9,201,3,40.100590,-82.925194,0.01,NaN,37.4,33.800000,100.0,29.62,...,False,False,False,False,False,False,False,False,False,False
10,201,3,39.952812,-83.119293,0.01,NaN,35.6,30.700000,93.0,29.64,...,False,False,False,False,False,False,False,False,False,False
11,241,3,39.932709,-82.830910,0.01,NaN,37.4,33.800000,100.0,29.62,...,False,True,False,False,False,False,False,False,False,False
12,201,2,39.737633,-84.149933,0.00,99.0,33.8,33.094733,100.0,29.63,...,False,False,False,False,False,False,False,False,False,False
13,201,2,39.790760,-84.241547,0.01,3198.0,36.0,31.100000,89.0,29.65,...,False,False,False,False,False,False,False,False,False,False
14,201,2,39.972038,-82.913521,0.01,3280.0,37.4,33.800000,100.0,29.62,...,False,False,False,False,False,False,False,False,True,False
15,201,2,39.745888,-84.170410,0.01,100.0,33.8,33.094733,100.0,29.63,...,False,False,False,False,False,False,False,False,False,False
16,201,2,39.748329,-84.224007,0.01,NaN,35.6,33.094733,99.0,29.65,...,False,False,False,False,False,False,False,False,False,False
17,201,2,39.752174,-84.239952,0.00,3001.0,36.0,31.100000,89.0,29.65,...,False,False,False,False,False,False,False,False,False,False
18,201,2,39.740669,-84.184135,0.01,440.0,37.4,32.100000,93.0,29.63,...,False,False,False,False,False,False,False,False,True,False
19,201,2,39.790703,-84.244461,0.01,3499.0,36.0,30.300000,89.0,29.65,...,False,False,False,False,False,False,False,False,False,False
20,201,2,40.052509,-82.882332,0.00,193.0,33.8,29.600000,100.0,29.62,...,False,False,False,False,False,False,False,False,False,False
21,201,2,39.773346,-84.224686,0.00,1391.0,36.0,30.300000,89.0,29.65,...,False,False,False,False,False,False,False,False,False,False
22,201,2,39.628288,-84.226151,0.01,NaN,35.1,28.600000,89.0,29.65,...,False,False,False,False,False,False,False,False,False,False
23,201,3,40.023487,-82.994888,0.01,NaN,37.0,32.400000,96.0,29.63,...,False,False,False,False,False,False,False,False,False,False
24,201,2,39.761379,-84.259216,0.01,4401.0,37.9,30.900000,76.0,29.62,...,False,False,False,False,False,False,False,False,False,False
25,201,2,40.158024,-82.641762,1.32,7849.0,37.9,34.400000,100.0,29.60,...,False,False,False,False,False,False,False,False,False,False
26,201,2,39.733219,-84.159653,0.00,1240.0,36.0,29.000000,86.0,29.63,...,False,False,False,False,False,False,False,False,True,False
27,201,2,39.775303,-84.200523,0.00,1.0,39.9,32.900000,70.0,29.61,...,False,False,False,False,False,False,False,False,False,False
28,201,2,39.789322,-84.239105,0.01,2198.0,39.9,34.500000,65.0,29.61,...,False,False,False,False,False,False,False,False,False,False
29,201,2,39.758720,-84.183762,0.00,500.0,39.2,35.900000,75.0,29.62,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,201,2,38.298931,-122.127220,0.01,5158.0,51.1,33.094733,43.0,30.07,...,False,False,False,False,False,False,False,False,False,False
9971,201,2,38.017372,-121.095589,0.01,18001.0,48.0,33.094733,54.0,30.09,...,False,False,False,False,False,False,False,False,False,False
9972,201,3,37.425724,-121.916618,0.01,NaN,52.0,33.094733,43.0,30.06,...,False,False,False,False,False,False,False,False,False,False
9973,201,3,37.719204,-121.660400,0.01,NaN,45.0,39.300000,53.0,30.08,...,False,False,False,False,False,False,False,False,False,False
9974,201,3,37.740494,-121.586182,0.01,NaN,45.0,39.300000,53.0,30.08,...,False,False,False,False,False,False,False,False,False,False
9975,201,3,39.202686,-120.809448,0.01,NaN,34.0,31.000000,70.0,30.07,...,False,False,False,False,False,False,False,False,False,False
9976,201,2,38.743801,-121.223297,0.00,4199.0,46.4,33.094733,62.0,30.11,...,False,False,False,False,False,False,False,False,True,False
9977,201,3,37.737553,-122.140717,0.01,NaN,48.0,33.094733,56.0,30.08,...,False,False,False,False,False,False,False,False,False,False
9978,201,2,37.901688,-121.467857,0.01,12115.0,48.0,33.094733,54.0,30.09,...,False,False,False,False,False,False,False,False,False,False
9979,201,2,37.609432,-120.993591,0.01,100.0,50.0,33.094733,46.0,30.10,...,False,False,False,False,False,False,False,False,False,False
9980,201,3,38.641464,-121.462387,0.01,NaN,46.4,33.094733,66.0,30.11,...,False,False,False,False,False,False,False,False,False,False
9981,241,3,37.923428,-122.359985,0.01,NaN,46.0,41.400000,58.0,30.03,...,False,False,False,False,False,False,False,False,False,False
9982,201,2,37.468502,-122.154770,0.01,NaN,50.0,33.094733,54.0,30.05,...,False,True,False,False,False,False,False,False,False,False
9983,241,2,36.756168,-121.665146,0.01,651.0,53.1,33.094733,59.0,30.04,...,False,False,False,False,False,False,False,False,False,False
9984,201,2,38.263973,-122.727852,0.01,5541.0,46.4,41.500000,57.0,30.07,...,False,False,False,False,False,False,False,False,False,False
9985,201,2,38.937988,-121.144455,0.01,8999.0,42.8,41.100000,81.0,30.05,...,False,False,False,False,False,False,False,False,False,False
9986,201,3,37.900543,-121.284927,0.01,NaN,48.0,33.094733,56.0,30.06,...,False,False,False,False,False,False,False,False,False,False
9987,201,3,37.842594,-122.297600,0.01,NaN,48.9,33.094733,56.0,30.06,...,False,True,False,False,False,False,False,False,False,False
9988,201,3,37.588799,-121.870750,3.54,NaN,43.0,37.200000,60.0,30.05,...,False,False,False,False,False,False,False,False,False,False
9989,201,2,37.241005,-121.797180,0.01,NaN,51.8,33.094733,50.0,30.05,...,False,False,False,False,False,False,False,False,False,False
9990,201,2,38.456692,-121.410385,0.01,NaN,46.0,41.900000,71.0,30.09,...,False,False,False,False,False,False,False,False,False,False
9991,201,2,38.245728,-122.625511,0.01,NaN,44.6,41.400000,61.0,30.07,...,False,True,False,False,False,False,False,False,False,False
9992,201,3,37.564606,-121.902275,0.01,NaN,43.0,37.200000,60.0,30.05,...,False,True,False,False,False,False,False,False,False,False
9993,201,3,38.744102,-121.270569,0.01,NaN,42.8,38.000000,76.0,30.11,...,False,False,False,False,False,False,False,False,False,False
9994,201,2,37.066490,-121.219147,0.01,NaN,48.2,33.094733,62.0,30.05,...,False,False,False,False,False,False,True,False,False,False
9995,201,2,38.701267,-121.077751,0.00,3108.0,46.4,33.094733,66.0,30.08,...,False,False,False,False,False,False,False,False,False,False
9996,201,2,36.981407,-122.011192,0.01,NaN,52.0,33.094733,59.0,30.05,...,False,False,False,False,False,True,False,False,False,False
9997,201,3,37.326691,-121.940720,0.01,NaN,51.1,33.094733,50.0,30.04,...,False,False,False,False,False,False,False,False,False,False
9998,201,3,37.930088,-122.324036,0.01,NaN,44.1,40.800000,63.0,30.04,...,False,False,False,False,False,False,False,False,False,False
9999,201,3,38.574406,-121.577354,0.01,NaN,46.0,41.900000,71.0,30.09,...,False,False,False,False,False,False,False,False,False,False

In [9]:
q=['Severity','Start_Lat','Start_Lng','Distance(mi)','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']
q

['Severity',
 'Start_Lat',
 'Start_Lng',
 'Distance(mi)',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)']

In [10]:
q=df[['Severity','Start_Lat','Start_Lng','Distance(mi)','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']]
q

,Severity,Start_Lat,Start_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
0,3,39.865147,-84.058723,0.01,36.9,NaN,91.0,29.68,10.0,NaN,0.02
1,2,39.928059,-82.831184,0.01,37.9,NaN,100.0,29.65,10.0,NaN,0.00
2,2,39.063148,-84.032608,0.01,36.0,33.3,100.0,29.67,10.0,3.5,NaN
3,3,39.747753,-84.205582,0.01,35.1,31.0,96.0,29.64,9.0,4.6,NaN
4,2,39.627781,-84.188354,0.01,36.0,33.3,89.0,29.65,6.0,3.5,NaN
5,3,40.100590,-82.925194,0.01,37.9,35.5,97.0,29.63,7.0,3.5,0.03
6,2,39.758274,-84.230507,0.00,34.0,31.0,100.0,29.66,7.0,3.5,NaN
7,3,39.770382,-84.194901,0.01,34.0,31.0,100.0,29.66,7.0,3.5,NaN
8,2,39.778061,-84.172005,0.00,33.3,NaN,99.0,29.67,5.0,1.2,NaN
9,3,40.100590,-82.925194,0.01,37.4,33.8,100.0,29.62,3.0,4.6,0.02
10,3,39.952812,-83.119293,0.01,35.6,30.7,93.0,29.64,5.0,5.8,NaN
11,3,39.932709,-82.830910,0.01,37.4,33.8,100.0,29.62,3.0,4.6,0.02
12,2,39.737633,-84.149933,0.00,33.8,NaN,100.0,29.63,3.0,2.3,NaN
13,2,39.790760,-84.241547,0.01,36.0,31.1,89.0,29.65,10.0,5.8,NaN
14,2,39.972038,-82.913521,0.01,37.4,33.8,100.0,29.62,3.0,4.6,0.02
15,2,39.745888,-84.170410,0.01,33.8,NaN,100.0,29.63,3.0,2.3,NaN
16,2,39.748329,-84.224007,0.01,35.6,NaN,99.0,29.65,7.0,2.3,NaN
17,2,39.752174,-84.239952,0.00,36.0,31.1,89.0,29.65,10.0,5.8,NaN
18,2,39.740669,-84.184135,0.01,37.4,32.1,93.0,29.63,10.0,6.9,NaN
19,2,39.790703,-84.244461,0.01,36.0,30.3,89.0,29.65,10.0,6.9,NaN
20,2,40.052509,-82.882332,0.00,33.8,29.6,100.0,29.62,2.0,4.6,0.01
21,2,39.773346,-84.224686,0.00,36.0,30.3,89.0,29.65,10.0,6.9,NaN
22,2,39.628288,-84.226151,0.01,35.1,28.6,89.0,29.65,6.0,8.1,0.02
23,3,40.023487,-82.994888,0.01,37.0,32.4,96.0,29.63,8.0,5.8,0.00
24,2,39.761379,-84.259216,0.01,37.9,30.9,76.0,29.62,10.0,10.4,NaN
25,2,40.158024,-82.641762,1.32,37.9,34.4,100.0,29.60,5.0,4.6,0.01
26,2,39.733219,-84.159653,0.00,36.0,29.0,86.0,29.63,7.0,9.2,0.00
27,2,39.775303,-84.200523,0.00,39.9,32.9,70.0,29.61,10.0,11.5,0.00
28,2,39.789322,-84.239105,0.01,39.9,34.5,65.0,29.61,10.0,8.1,NaN
29,2,39.758720,-84.183762,0.00,39.2,35.9,75.0,29.62,10.0,4.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...
9970,2,38.298931,-122.127220,0.01,51.1,NaN,43.0,30.07,10.0,13.8,NaN
9971,2,38.017372,-121.095589,0.01,48.0,NaN,54.0,30.09,10.0,5.8,NaN
9972,3,37.425724,-121.916618,0.01,52.0,NaN,43.0,30.06,10.0,NaN,NaN
9973,3,37.719204,-121.660400,0.01,45.0,39.3,53.0,30.08,10.0,11.5,NaN
9974,3,37.740494,-121.586182,0.01,45.0,39.3,53.0,30.08,10.0,11.5,NaN
9975,3,39.202686,-120.809448,0.01,34.0,31.0,70.0,30.07,10.0,3.5,NaN
9976,2,38.743801,-121.223297,0.00,46.4,NaN,62.0,30.11,10.0,NaN,NaN
9977,3,37.737553,-122.140717,0.01,48.0,NaN,56.0,30.08,10.0,8.1,NaN
9978,2,37.901688,-121.467857,0.01,48.0,NaN,54.0,30.09,10.0,5.8,NaN
9979,2,37.609432,-120.993591,0.01,50.0,NaN,46.0,30.10,10.0,3.5,NaN
9980,3,38.641464,-121.462387,0.01,46.4,NaN,66.0,30.11,10.0,NaN,NaN
9981,3,37.923428,-122.359985,0.01,46.0,41.4,58.0,30.03,10.0,9.2,NaN
9982,2,37.468502,-122.154770,0.01,50.0,NaN,54.0,30.05,10.0,6.9,NaN
9983,2,36.756168,-121.665146,0.01,53.1,NaN,59.0,30.04,10.0,12.7,NaN
9984,2,38.263973,-122.727852,0.01,46.4,41.5,57.0,30.07,10.0,10.4,NaN
9985,2,38.937988,-121.144455,0.01,42.8,41.1,81.0,30.05,10.0,3.5,NaN
9986,3,37.900543,-121.284927,0.01,48.0,NaN,56.0,30.06,10.0,5.8,NaN
9987,3,37.842594,-122.297600,0.01,48.9,NaN,56.0,30.06,10.0,3.5,NaN
9988,3,37.588799,-121.870750,3.54,43.0,37.2,60.0,30.05,10.0,10.4,NaN
9989,2,37.241005,-121.797180,0.01,51.8,NaN,50.0,30.05,10.0,NaN,NaN
9990,2,38.456692,-121.410385,0.01,46.0,41.9,71.0,30.09,10.0,8.1,NaN
9991,2,38.245728,-122.625511,0.01,44.6,41.4,61.0,30.07,10.0,5.8,NaN
9992,3,37.564606,-121.902275,0.01,43.0,37.2,60.0,30.05,10.0,10.4,NaN
9993,3,38.744102,-121.270569,0.01,42.8,38.0,76.0,30.11,10.0,8.1,NaN
9994,2,37.066490,-121.219147,0.01,48.2,NaN,62.0,30.05,10.0,11.5,NaN
9995,2,38.701267,-121.077751,0.00,46.4,NaN,66.0,30.08,10.0,NaN,NaN
9996,2,36.981407,-122.011192,0.01,52.0,NaN,59.0,30.05,10.0,6.9,NaN
9997,3,37.326691,-121.940720,0.01,51.1,NaN,50.0,30.04,10.0,5.8,NaN
9998,3,37.930088,-122.324036,0.01,44.1,40.8,63.0,30.04,10.0,5.8,NaN
9999,3,38.574406,-121.577354,0.01,46.0,41.9,71.0,30.09,10.0,8.1,NaN

In [19]:
q.to_csv(r'F:\Abhishek\3rd sem\Introduction to data science\numeric.csv',index=False)

In [13]:
df.shape

(10000, 47)

In [11]:
q

,Severity,Start_Lat,Start_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
0,3,39.865147,-84.058723,0.01,36.9,NaN,91.0,29.68,10.0,NaN,0.02
1,2,39.928059,-82.831184,0.01,37.9,NaN,100.0,29.65,10.0,NaN,0.00
2,2,39.063148,-84.032608,0.01,36.0,33.3,100.0,29.67,10.0,3.5,NaN
3,3,39.747753,-84.205582,0.01,35.1,31.0,96.0,29.64,9.0,4.6,NaN
4,2,39.627781,-84.188354,0.01,36.0,33.3,89.0,29.65,6.0,3.5,NaN
5,3,40.100590,-82.925194,0.01,37.9,35.5,97.0,29.63,7.0,3.5,0.03
6,2,39.758274,-84.230507,0.00,34.0,31.0,100.0,29.66,7.0,3.5,NaN
7,3,39.770382,-84.194901,0.01,34.0,31.0,100.0,29.66,7.0,3.5,NaN
8,2,39.778061,-84.172005,0.00,33.3,NaN,99.0,29.67,5.0,1.2,NaN
9,3,40.100590,-82.925194,0.01,37.4,33.8,100.0,29.62,3.0,4.6,0.02
10,3,39.952812,-83.119293,0.01,35.6,30.7,93.0,29.64,5.0,5.8,NaN
11,3,39.932709,-82.830910,0.01,37.4,33.8,100.0,29.62,3.0,4.6,0.02
12,2,39.737633,-84.149933,0.00,33.8,NaN,100.0,29.63,3.0,2.3,NaN
13,2,39.790760,-84.241547,0.01,36.0,31.1,89.0,29.65,10.0,5.8,NaN
14,2,39.972038,-82.913521,0.01,37.4,33.8,100.0,29.62,3.0,4.6,0.02
15,2,39.745888,-84.170410,0.01,33.8,NaN,100.0,29.63,3.0,2.3,NaN
16,2,39.748329,-84.224007,0.01,35.6,NaN,99.0,29.65,7.0,2.3,NaN
17,2,39.752174,-84.239952,0.00,36.0,31.1,89.0,29.65,10.0,5.8,NaN
18,2,39.740669,-84.184135,0.01,37.4,32.1,93.0,29.63,10.0,6.9,NaN
19,2,39.790703,-84.244461,0.01,36.0,30.3,89.0,29.65,10.0,6.9,NaN
20,2,40.052509,-82.882332,0.00,33.8,29.6,100.0,29.62,2.0,4.6,0.01
21,2,39.773346,-84.224686,0.00,36.0,30.3,89.0,29.65,10.0,6.9,NaN
22,2,39.628288,-84.226151,0.01,35.1,28.6,89.0,29.65,6.0,8.1,0.02
23,3,40.023487,-82.994888,0.01,37.0,32.4,96.0,29.63,8.0,5.8,0.00
24,2,39.761379,-84.259216,0.01,37.9,30.9,76.0,29.62,10.0,10.4,NaN
25,2,40.158024,-82.641762,1.32,37.9,34.4,100.0,29.60,5.0,4.6,0.01
26,2,39.733219,-84.159653,0.00,36.0,29.0,86.0,29.63,7.0,9.2,0.00
27,2,39.775303,-84.200523,0.00,39.9,32.9,70.0,29.61,10.0,11.5,0.00
28,2,39.789322,-84.239105,0.01,39.9,34.5,65.0,29.61,10.0,8.1,NaN
29,2,39.758720,-84.183762,0.00,39.2,35.9,75.0,29.62,10.0,4.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...
9970,2,38.298931,-122.127220,0.01,51.1,NaN,43.0,30.07,10.0,13.8,NaN
9971,2,38.017372,-121.095589,0.01,48.0,NaN,54.0,30.09,10.0,5.8,NaN
9972,3,37.425724,-121.916618,0.01,52.0,NaN,43.0,30.06,10.0,NaN,NaN
9973,3,37.719204,-121.660400,0.01,45.0,39.3,53.0,30.08,10.0,11.5,NaN
9974,3,37.740494,-121.586182,0.01,45.0,39.3,53.0,30.08,10.0,11.5,NaN
9975,3,39.202686,-120.809448,0.01,34.0,31.0,70.0,30.07,10.0,3.5,NaN
9976,2,38.743801,-121.223297,0.00,46.4,NaN,62.0,30.11,10.0,NaN,NaN
9977,3,37.737553,-122.140717,0.01,48.0,NaN,56.0,30.08,10.0,8.1,NaN
9978,2,37.901688,-121.467857,0.01,48.0,NaN,54.0,30.09,10.0,5.8,NaN
9979,2,37.609432,-120.993591,0.01,50.0,NaN,46.0,30.10,10.0,3.5,NaN
9980,3,38.641464,-121.462387,0.01,46.4,NaN,66.0,30.11,10.0,NaN,NaN
9981,3,37.923428,-122.359985,0.01,46.0,41.4,58.0,30.03,10.0,9.2,NaN
9982,2,37.468502,-122.154770,0.01,50.0,NaN,54.0,30.05,10.0,6.9,NaN
9983,2,36.756168,-121.665146,0.01,53.1,NaN,59.0,30.04,10.0,12.7,NaN
9984,2,38.263973,-122.727852,0.01,46.4,41.5,57.0,30.07,10.0,10.4,NaN
9985,2,38.937988,-121.144455,0.01,42.8,41.1,81.0,30.05,10.0,3.5,NaN
9986,3,37.900543,-121.284927,0.01,48.0,NaN,56.0,30.06,10.0,5.8,NaN
9987,3,37.842594,-122.297600,0.01,48.9,NaN,56.0,30.06,10.0,3.5,NaN
9988,3,37.588799,-121.870750,3.54,43.0,37.2,60.0,30.05,10.0,10.4,NaN
9989,2,37.241005,-121.797180,0.01,51.8,NaN,50.0,30.05,10.0,NaN,NaN
9990,2,38.456692,-121.410385,0.01,46.0,41.9,71.0,30.09,10.0,8.1,NaN
9991,2,38.245728,-122.625511,0.01,44.6,41.4,61.0,30.07,10.0,5.8,NaN
9992,3,37.564606,-121.902275,0.01,43.0,37.2,60.0,30.05,10.0,10.4,NaN
9993,3,38.744102,-121.270569,0.01,42.8,38.0,76.0,30.11,10.0,8.1,NaN
9994,2,37.066490,-121.219147,0.01,48.2,NaN,62.0,30.05,10.0,11.5,NaN
9995,2,38.701267,-121.077751,0.00,46.4,NaN,66.0,30.08,10.0,NaN,NaN
9996,2,36.981407,-122.011192,0.01,52.0,NaN,59.0,30.05,10.0,6.9,NaN
9997,3,37.326691,-121.940720,0.01,51.1,NaN,50.0,30.04,10.0,5.8,NaN
9998,3,37.930088,-122.324036,0.01,44.1,40.8,63.0,30.04,10.0,5.8,NaN
9999,3,38.574406,-121.577354,0.01,46.0,41.9,71.0,30.09,10.0,8.1,NaN

In [5]:
q.shape

NameError: name 'q' is not defined

In [54]:
tables=pd.crosstab(q['Severity'],q['Distance(mi)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 62.605 p_value 1.000

In [55]:
tables=pd.crosstab(q['Temperature(F)'],q['Humidity(%)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 104776.815 p_value 0.000

In [56]:
tables=pd.crosstab(q['Start_Lat'],q['Pressure(in)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 826500.786 p_value 0.000

In [57]:
tables=pd.crosstab(q['Humidity(%)'],q['Pressure(in)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 21727.217 p_value 0.000

In [58]:
tables=pd.crosstab(q['Severity'],q['Temperature(F)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 895.295 p_value 0.000

In [59]:
tables=pd.crosstab(q['Severity'],q['Distance(mi)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 62.605 p_value 1.000

In [60]:
tables=pd.crosstab(q['Wind_Chill(F)'],q['Distance(mi)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 9957.961 p_value 0.000

In [61]:
tables=pd.crosstab(q['Start_Lat'],q['Start_Lng'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 61933932.540 p_value 0.000

In [12]:
pd.crosstab(q['Severity'],q['Distance(mi)'])

Distance(mi),0.0,0.01,0.13,0.33,0.48,0.57,0.59,0.6,0.61,0.67,...,5.15,7.07,7.78,8.25,9.86,10.88,11.93,12.18,14.08,24.04
Severity,,,,,,,,,,,,,,,,,,,,,
1,4,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2996,3029,1,1,1,0,0,0,0,1,...,1,0,1,1,1,0,1,1,1,1
3,1828,2087,0,0,0,1,1,1,1,0,...,0,1,0,0,0,1,0,0,0,0
4,4,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
from scipy.stats import chi2_contingency

In [16]:
chi2_contingency(pd.crosstab(q['Severity'],q['Distance(mi)']))

(62.604833059065896,
 0.9999999556733775,
 132,
 array([[2.8992000e+00, 3.0720000e+00, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 2.4000000e-03, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         1.2000000e-03, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         1.2000000e-03, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04],
        [2.9219104e+03, 3.0960640e+03, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 2.4188000e+00, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         1.2094000e+00, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         1.2094000e+00, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01],
        [1.9042912e+03, 2.0177920e+03, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 1.5764000e+00, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         7.8820000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         7.8820000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01, 3.9410000e-01, 3.9410000e-01, 3.9410000e-01,
         3.9410000e-01],
        [2.8992000e+00, 3.0720000e+00, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 2.4000000e-03, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         1.2000000e-03, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         1.2000000e-03, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04]]))

In [23]:
pd.crosstab(df['Wind_Direction'],df['Weather_Condition'])

Weather_Condition,Clear,Drizzle,Fog,Haze,Heavy Rain,Light Drizzle,Light Freezing Drizzle,Light Freezing Fog,Light Freezing Rain,Light Haze,...,Mist,Mostly Cloudy,Overcast,Partly Cloudy,Patches of Fog,Rain,Scattered Clouds,Shallow Fog,Smoke,Snow
Wind_Direction,,,,,,,,,,,,,,,,,,,,,
Calm,1022,0,8,38,3,0,0,0,0,0,...,5,140,241,60,0,3,78,2,0,0
ENE,86,0,0,0,2,0,0,0,0,0,...,0,23,18,12,0,6,1,0,0,0
ESE,91,0,1,9,2,0,0,0,0,0,...,0,38,64,15,0,9,4,0,0,1
East,123,1,0,11,1,1,0,0,0,0,...,0,17,37,12,0,10,18,0,0,0
NE,82,0,0,0,1,0,0,0,1,0,...,0,15,23,15,0,7,13,1,0,0
NNE,87,0,0,4,0,0,0,0,0,0,...,0,16,24,25,0,6,8,0,0,0
NNW,387,0,1,3,0,0,0,0,0,0,...,2,24,68,35,0,1,14,1,0,0
NW,457,0,0,4,0,0,0,0,0,0,...,0,37,68,89,0,3,41,0,0,1
North,288,0,1,2,0,0,0,0,0,0,...,0,18,75,32,0,5,25,0,1,0
SE,120,0,0,8,2,0,6,0,0,1,...,0,51,79,13,0,7,13,0,0,0
SSE,144,0,2,6,2,0,2,0,0,0,...,2,39,139,17,0,22,12,0,0,1
SSW,418,0,0,2,0,0,2,0,0,0,...,0,25,77,15,0,4,18,0,0,0
SW,325,0,0,3,0,2,0,0,0,0,...,2,24,45,18,0,5,15,0,0,0
South,463,0,0,16,4,0,0,2,0,0,...,0,38,161,25,0,21,30,0,0,3
Variable,194,0,0,2,0,0,0,0,0,0,...,0,22,25,24,2,0,11,0,0,0
WNW,542,0,0,12,0,0,0,0,0,0,...,0,63,96,200,0,2,68,0,1,0
WSW,181,0,0,4,0,0,0,0,0,0,...,0,25,63,24,0,0,21,0,0,1
West,485,0,2,10,1,0,0,0,0,0,...,0,85,100,135,0,1,57,0,0,0

In [24]:
chi2_contingency(pd.crosstab(df['Wind_Direction'],df['Weather_Condition']))

(2296.1567270209725,
 5.528483547174103e-273,
 374,
 array([[9.27187783e+02, 1.68732991e-01, 2.53099486e+00, 2.26102207e+01,
         3.03719383e+00, 5.06198972e-01, 1.68732991e+00, 3.37465981e-01,
         1.68732991e-01, 1.68732991e-01, 1.14063502e+02, 1.68732991e-01,
         1.85606290e+01, 1.85606290e+00, 1.18113093e+02, 2.36732386e+02,
         1.29249471e+02, 3.37465981e-01, 1.88980950e+01, 7.54236468e+01,
         6.74931963e-01, 3.37465981e-01, 1.18113093e+00],
        [9.24972281e+01, 1.68329805e-02, 2.52494708e-01, 2.25561939e+00,
         3.02993650e-01, 5.04989416e-02, 1.68329805e-01, 3.36659611e-02,
         1.68329805e-02, 1.68329805e-02, 1.13790948e+01, 1.68329805e-02,
         1.85162786e+00, 1.85162786e-01, 1.17830864e+01, 2.36166717e+01,
         1.28940631e+01, 3.36659611e-02, 1.88529382e+00, 7.52434230e+00,
         6.73319222e-02, 3.36659611e-02, 1.17830864e-01],
        [1.48992541e+02, 2.71142022e-02, 4.06713033e-01, 3.63330309e+00,
         4.88055640e-01, 8.13426066e-02, 2.71142022e-01, 5.42284044e-02,
         2.71142022e-02, 2.71142022e-02, 1.83292007e+01, 2.71142022e-02,
         2.98256224e+00, 2.98256224e-01, 1.89799415e+01, 3.80412257e+01,
         2.07694789e+01, 5.42284044e-02, 3.03679065e+00, 1.21200484e+01,
         1.08456809e-01, 5.42284044e-02, 1.89799415e-01],
        [1.46223163e+02, 2.66102207e-02, 3.99153311e-01, 3.56576958e+00,
         4.78983973e-01, 7.98306622e-02, 2.66102207e-01, 5.32204415e-02,
         2.66102207e-02, 2.66102207e-02, 1.79885092e+01, 2.66102207e-02,
         2.92712428e+00, 2.92712428e-01, 1.86271545e+01, 3.73341397e+01,
         2.03834291e+01, 5.32204415e-02, 2.98034472e+00, 1.18947687e+01,
         1.06440883e-01, 5.32204415e-02, 1.86271545e-01],
        [9.13894769e+01, 1.66313880e-02, 2.49470819e-01, 2.22860599e+00,
         2.99364983e-01, 4.98941639e-02, 1.66313880e-01, 3.32627759e-02,
         1.66313880e-02, 1.66313880e-02, 1.12428183e+01, 1.66313880e-02,
         1.82945268e+00, 1.82945268e-01, 1.16419716e+01, 2.33338373e+01,
         1.27396432e+01, 3.32627759e-02, 1.86271545e+00, 7.43423042e+00,
         6.65255519e-02, 3.32627759e-02, 1.16419716e-01],
        [9.91437355e+01, 1.80425360e-02, 2.70638041e-01, 2.41769983e+00,
         3.24765649e-01, 5.41276081e-02, 1.80425360e-01, 3.60850721e-02,
         1.80425360e-02, 1.80425360e-02, 1.21967544e+01, 1.80425360e-02,
         1.98467896e+00, 1.98467896e-01, 1.26297752e+01, 2.53136781e+01,
         1.38205826e+01, 3.60850721e-02, 2.02076404e+00, 8.06501361e+00,
         7.21701441e-02, 3.60850721e-02, 1.26297752e-01],
        [3.15709102e+02, 5.74538857e-02, 8.61808285e-01, 7.69882068e+00,
         1.03416994e+00, 1.72361657e-01, 5.74538857e-01, 1.14907771e-01,
         5.74538857e-02, 5.74538857e-02, 3.88388267e+01, 5.74538857e-02,
         6.31992743e+00, 6.31992743e-01, 4.02177200e+01, 8.06078016e+01,
         4.40096764e+01, 1.14907771e-01, 6.43483520e+00, 2.56818869e+01,
         2.29815543e-01, 1.14907771e-01, 4.02177200e-01],
        [4.05990828e+02, 7.38836811e-02, 1.10825522e+00, 9.90041326e+00,
         1.32990626e+00, 2.21651043e-01, 7.38836811e-01, 1.47767362e-01,
         7.38836811e-02, 7.38836811e-02, 4.99453684e+01, 7.38836811e-02,
         8.12720492e+00, 8.12720492e-01, 5.17185768e+01, 1.03658805e+02,
         5.65948997e+01, 1.47767362e-01, 8.27497228e+00, 3.30260054e+01,
         2.95534724e-01, 1.47767362e-01, 5.17185768e-01],
        [2.66414172e+02, 4.84830158e-02, 7.27245237e-01, 6.49672412e+00,
         8.72694285e-01, 1.45449047e-01, 4.84830158e-01, 9.69660317e-02,
         4.84830158e-02, 4.84830158e-02, 3.27745187e+01, 4.84830158e-02,
         5.33313174e+00, 5.33313174e-01, 3.39381111e+01, 6.80216712e+01,
         3.71379901e+01, 9.69660317e-02, 5.43009777e+00, 2.16719081e+01,
         1.93932063e-01, 9.69660317e-02, 3.39381111e-01],
        [2.23765749e+02, 4.07217014e-02, 6.10825522e-01, 5.45670799e+00,
         7.32990626e-01, 1.22165104e-01, 4.07217014e-01, 8.14434029e-02,
         4.07217014e-02, 4.07217014e-02, 2.75278702e+01, 4.07217014e-02,
         4.47938716e+00, 4.47938716e-01, 2.85051910e+01, 5.71325471e+01,
         3.11928233e+01, 8.14434029e-02, 4.56083056e+00, 1.82026005e+01,
         1.62886806e-01, 8.14434029e-02, 2.85051910e-01],
        [2.86907570e+02, 5.22124786e-02, 7.83187179e-01, 6.99647213e+00,
         9.39824614e-01, 1.56637436e-01, 5.22124786e-01, 1.04424957e-01,
         5.22124786e-02, 5.22124786e-02, 3.52956355e+01, 5.22124786e-02,
         5.74337264e+00, 5.74337264e-01, 3.65487350e+01, 7.32541074e+01,
         3.99947586e+01, 1.04424957e-01, 5.84779760e+00, 2.33389779e+01,
         2.08849914e-01, 1.04424957e-01, 3.65487350e-01],
        [3.32879246e+02, 6.05785707e-02, 9.08678561e-01, 8.11752847e+00,
         1.09041427e+00, 1.81735712e-01, 6.05785707e-01, 1.21157141e-01,
         6.05785707e-02, 6.05785707e-02, 4.09511138e+01, 6.05785707e-02,
         6.66364278e+00, 6.66364278e-01, 4.24049995e+01, 8.49917347e+01,
         4.64031852e+01, 1.21157141e-01, 6.78479992e+00, 2.70786211e+01,
         2.42314283e-01, 1.21157141e-01, 4.24049995e-01],
        [2.65860296e+02, 4.83822195e-02, 7.25733293e-01, 6.48321742e+00,
         8.70879952e-01, 1.45146659e-01, 4.83822195e-01, 9.67644391e-02,
         4.83822195e-02, 4.83822195e-02, 3.27063804e+01, 4.83822195e-02,
         5.32204415e+00, 5.32204415e-01, 3.38675537e+01, 6.78802540e+01,
         3.70607802e+01, 9.67644391e-02, 5.41880859e+00, 2.16268521e+01,
         1.93528878e-01, 9.67644391e-02, 3.38675537e-01],
        [4.68578772e+02, 8.52736619e-02, 1.27910493e+00, 1.14266707e+01,
         1.53492591e+00, 2.55820986e-01, 8.52736619e-01, 1.70547324e-01,
         8.52736619e-02, 8.52736619e-02, 5.76449955e+01, 8.52736619e-02,
         9.38010281e+00, 9.38010281e-01, 5.96915634e+01, 1.19638948e+02,
         6.53196250e+01, 1.70547324e-01, 9.55065014e+00, 3.81173269e+01,
         3.41094648e-01, 1.70547324e-01, 5.96915634e-01],
        [1.57300675e+02, 2.86261466e-02, 4.29392198e-01, 3.83590364e+00,
         5.15270638e-01, 8.58784397e-02, 2.86261466e-01, 5.72522931e-02,
         2.86261466e-02, 2.86261466e-02, 1.93512751e+01, 2.86261466e-02,
         3.14887612e+00, 3.14887612e-01, 2.00383026e+01, 4.01624836e+01,
         2.19276283e+01, 5.72522931e-02, 3.20612841e+00, 1.27958875e+01,
         1.14504586e-01, 5.72522931e-02, 2.00383026e-01],
        [5.57198871e+02, 1.01401068e-01, 1.52101603e+00, 1.35877432e+01,
         1.82521923e+00, 3.04203205e-01, 1.01401068e+00, 2.02802137e-01,
         1.01401068e-01, 1.01401068e-01, 6.85471223e+01, 1.01401068e-01,
         1.11541175e+01, 1.11541175e+00, 7.09807479e+01, 1.42265699e+02,
         7.76732184e+01, 2.02802137e-01, 1.13569197e+01, 4.53262776e+01,
         4.05604274e-01, 2.02802137e-01, 7.09807479e-01],
        [1.96625844e+02, 3.57826832e-02, 5.36740248e-01, 4.79487955e+00,
         6.44088298e-01, 1.07348050e-01, 3.57826832e-01, 7.15653664e-02,
         3.57826832e-02, 3.57826832e-02, 2.41890938e+01, 3.57826832e-02,
         3.93609515e+00, 3.93609515e-01, 2.50478782e+01, 5.02031045e+01,
         2.74095353e+01, 7.15653664e-02, 4.00766052e+00, 1.59948594e+01,
         1.43130733e-01, 7.15653664e-02, 2.50478782e-01],
        [5.12334946e+02, 9.32365689e-02, 1.39854853e+00, 1.24937002e+01,
         1.67825824e+00, 2.79709707e-01, 9.32365689e-01, 1.86473138e-01,
         9.32365689e-02, 9.32365689e-02, 6.30279206e+01, 9.32365689e-02,
         1.02560226e+01, 1.02560226e+00, 6.52655982e+01, 1.30810906e+02,
         7.14192118e+01, 1.86473138e-01, 1.04424957e+01, 4.16767463e+01,
         3.72946276e-01, 1.86473138e-01, 6.52655982e-01]]))

In [28]:
pd.crosstab(df['Wind_Direction'],df['State'])

State             CA  OH  WV
Wind_Direction
Calm            1648  29   0
ENE              141  27   0
ESE              255  15   0
East             240  24   0
NE               121  44   0
NNE              155  24   0
NNW              544  27   0
NW               691  43   0
North            480  26   0
SE               365  39   0
SSE              478  40   0
SSW              533  71   0
SW               423  62   0
South            776  70   0
Variable         281   3   0
WNW              955  55   0
WSW              300  54   1
West             856  71   0

In [29]:
chi2_contingency(pd.crosstab(df['Wind_Direction'],df['State']))

(338.1637688462235,
 8.719374310272517e-52,
 34,
 array([[1.55501495e+03, 1.21816795e+02, 1.68255242e-01],
        [1.55779673e+02, 1.22034715e+01, 1.68556236e-02],
        [2.50360189e+02, 1.96127220e+01, 2.70893950e-02],
        [2.44796629e+02, 1.91768837e+01, 2.64874084e-02],
        [1.52997893e+02, 1.19855523e+01, 1.65546303e-02],
        [1.65979532e+02, 1.30025083e+01, 1.79592656e-02],
        [5.29465436e+02, 4.14772750e+01, 5.72890539e-02],
        [6.80608809e+02, 5.33175479e+01, 7.36430220e-02],
        [4.69193539e+02, 3.67556938e+01, 5.07675329e-02],
        [3.74613023e+02, 2.93464433e+01, 4.05337614e-02],
        [4.80320658e+02, 3.76273703e+01, 5.19715060e-02],
        [5.60065015e+02, 4.38743855e+01, 6.05999799e-02],
        [4.49721080e+02, 3.52302599e+01, 4.86605799e-02],
        [7.84461924e+02, 6.14531955e+01, 8.48801043e-02],
        [2.63341828e+02, 2.06296779e+01, 2.84940303e-02],
        [9.36532557e+02, 7.33661082e+01, 1.01334404e-01],
        [3.29177285e+02, 2.57870974e+01, 3.56175379e-02],
        [8.59569981e+02, 6.73370121e+01, 9.30069228e-02]]))

In [32]:
pd.crosstab(df['Timezone'],df['State'])

State         CA   OH  WV
Timezone
US/Eastern     0  726   2
US/Pacific  9271    0   0

In [33]:
chi2_contingency(pd.crosstab(df['Timezone'],df['State']))

(9999.0, 0.0, 2, array([[6.74996300e+02, 5.28580858e+01, 1.45614561e-01],
        [8.59600370e+03, 6.73141914e+02, 1.85438544e+00]]))

In [34]:
chi2_contingency(pd.crosstab(df['Sunrise_Sunset'],df['State']))

(44.275330206153605,
 2.4307159093495694e-10,
 2,
 array([[5.5919432e+03, 4.3785060e+02, 1.2062000e+00],
        [3.6800568e+03, 2.8814940e+02, 7.9380000e-01]]))

In [35]:
chi2_contingency(pd.crosstab(df['Civil_Twilight'],df['State']))

(90.73510544928801,
 1.9820846318771448e-20,
 2,
 array([[5.9554056e+03, 4.6630980e+02, 1.2846000e+00],
        [3.3165944e+03, 2.5969020e+02, 7.1540000e-01]]))

In [36]:
chi2_contingency(pd.crosstab(df['Nautical_Twilight'],df['State']))

(146.36659462237992,
 1.647774623614261e-32,
 2,
 array([[6.2502552e+03, 4.8939660e+02, 1.3482000e+00],
        [3.0217448e+03, 2.3660340e+02, 6.5180000e-01]]))

In [37]:
chi2_contingency(pd.crosstab(df['Astronomical_Twilight'],df['State']))

(157.09257064087984,
 7.72292311609932e-35,
 2,
 array([[6.6378248e+03, 5.1974340e+02, 1.4318000e+00],
        [2.6341752e+03, 2.0625660e+02, 5.6820000e-01]]))

In [38]:
chi2_contingency(pd.crosstab(df['Civil_Twilight'],df['Street']))

(2430.327967168202,
 0.02531022509359213,
 2296,
 array([[1.2846, 0.6423, 0.6423, ..., 1.2846, 1.2846, 0.6423],
        [0.7154, 0.3577, 0.3577, ..., 0.7154, 0.7154, 0.3577]]))

In [40]:
pd.crosstab(df['Astronomical_Twilight'],df['Street'])

Street,10th St,13th St,15th Ave,15th St,164th Ave,165th Ave,16th St,17th Ave,17th St,19th Ave,...,Wyda Way,Wyoming St,X Street Broadway Aly,Yerba Buena Rd,Yolo Ave,Yosemite Blvd,Zangol Pl,Zinfandel Dr,Zinfandel Ln,Zygmunt Dr
Astronomical_Twilight,,,,,,,,,,,,,,,,,,,,,
Day,1,0,1,1,0,1,6,2,2,1,...,0,2,1,2,1,1,1,1,2,1
Night,1,1,0,0,1,1,0,1,2,0,...,1,0,0,3,0,3,0,1,0,0

In [41]:
chi2_contingency(pd.crosstab(df['Astronomical_Twilight'],df['Street']))

(2402.345907686875,
 0.05990691041468629,
 2296,
 array([[1.4318, 0.7159, 0.7159, ..., 1.4318, 1.4318, 0.7159],
        [0.5682, 0.2841, 0.2841, ..., 0.5682, 0.5682, 0.2841]]))

In [42]:
pd.crosstab(df['Nautical_Twilight'],df['Street'])

Street,10th St,13th St,15th Ave,15th St,164th Ave,165th Ave,16th St,17th Ave,17th St,19th Ave,...,Wyda Way,Wyoming St,X Street Broadway Aly,Yerba Buena Rd,Yolo Ave,Yosemite Blvd,Zangol Pl,Zinfandel Dr,Zinfandel Ln,Zygmunt Dr
Nautical_Twilight,,,,,,,,,,,,,,,,,,,,,
Day,1,0,1,1,0,1,5,2,2,1,...,0,2,1,1,1,1,1,1,2,1
Night,1,1,0,0,1,1,1,1,2,0,...,1,0,0,4,0,3,0,1,0,0

In [43]:
chi2_contingency(pd.crosstab(df['Nautical_Twilight'],df['Street']))

(2440.9383887075387,
 0.01763565681955304,
 2296,
 array([[1.3482, 0.6741, 0.6741, ..., 1.3482, 1.3482, 0.6741],
        [0.6518, 0.3259, 0.3259, ..., 0.6518, 0.6518, 0.3259]]))